#!/bin/bash
#SBATCH --job-name=buffer
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --partition=gpu_a100 
#SBATCH --gpus-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --output=logs/buffer-%j.out
#SBATCH --error=logs/buffer-%j.err

module purge
module load 2023
module load CUDA/12.4.0
module load Python/3.11.3-GCCcore-12.3.0

source $HOME/ednet_env/bin/activate
cd $HOME/scriptie

python inspect_replay_buffer.py /home/ddwilde/scriptie/runs/dota-replay/stage1-replay/replay/buffer.pt
python inspect_replay_buffer.py /home/ddwilde/scriptie/runs/dota-replay/stage2-replay/replay/buffer.pt
python inspect_replay_buffer.py /home/ddwilde/scriptie/runs/dota-replay/stage3-replay/replay/buffer.pt
