#!/bin/bash
#SBATCH --job-name=ednet_train
#SBATCH --partition=gpu_a100        # or the GPU partition available
#SBATCH --gres=gpu:1           # request 1 GPU (adjust if you want more)
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8      # or more, depending on data loading
#SBATCH --mem=32G              # adjust to your needs
#SBATCH --time=10:00:00        # hh:mm:ss – adjust based on how long training takes
#SBATCH --output=logs/test.out
#SBATCH --error=logs/test.err
# Load necessary modules
module purge
module load 2025
module load CUDA/12.8.0
source $HOME/ednet_env/bin/activate   # or however your env is set up

# Run training
python $HOME/scriptie/train.py --data MVRSD.yaml \
                --epochs 50 \
                --cfg 'ednet-s.yaml' \
                --imgsz 640 \
                --weights /home/ddwilde/scriptie/pretrained/small.pt   # or whatever variant you want
