#!/bin/bash
#SBATCH --job-name=mvrsd-setup
#SBATCH --time=02:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH --gpus-per-node=1
#SBATCH --mem=16G
#SBATCH --partition=gpu_a100 
#SBATCH --output=logs/mvrsd-setup-%j.out
#SBATCH --error=logs/mvrsd-setup-%j.err

module purge
module load 2023
module load Python/3.11.3-GCCcore-12.3.0

source $HOME/ednet_env/bin/activate
cd $HOME/scriptie


# Build Stage 1 memory (ex: 25 images per Stage 1 class)
python scripts/build_memory_dataset.py \
  --images /home/ddwilde/scriptie/datasets/dota-stage1/train/images \
  --labels /home/ddwilde/scriptie/datasets/dota-stage1/train/labels \
  --dest /home/ddwilde/scriptie/datasets/memory/stage1 \
  --classes 10 9 11 12 \
  --per-class 25