#!/bin/bash
#SBATCH --job-name=testset_dota
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --partition=gpu_a100 
#SBATCH --gpus-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --output=logs/testset_dota.out
#SBATCH --error=logs/testset_dota.err

module purge
module load 2023
module load CUDA/12.4.0
module load Python/3.11.3-GCCcore-12.3.0

source $HOME/ednet_env/bin/activate
cd $HOME/scriptie

python val.py --weights /home/ddwilde/scriptie/runs/dota_saab/stage1-saab/weights/best.pt \
              --data /home/ddwilde/scriptie/yaml/DOTA-stage1.yaml \
              --split test \
              --outdir /home/ddwilde/scriptie/results/test_stage1_saab

python val.py --weights /home/ddwilde/scriptie/runs/dota_lower/stage1-lower/weights/best.pt \
              --data /home/ddwilde/scriptie/yaml/DOTA-stage1.yaml \
              --split test \
              --outdir /home/ddwilde/scriptie/results/test_stage1_lower

mv /home/ddwilde/scriptie/datasets/dota-yolo-stage1/test/images/ /home/ddwilde/scriptie/datasets/dota-yolo-stage2/test/
mv /home/ddwilde/scriptie/datasets/dota-yolo-stage1/train/images/ /home/ddwilde/scriptie/datasets/dota-yolo-stage2/train/
mv /home/ddwilde/scriptie/datasets/dota-yolo-stage1/val/images/ /home/ddwilde/scriptie/datasets/dota-yolo-stage2/val/

python val.py --weights /home/ddwilde/scriptie/runs/dota_saab/stage2-saab/weights/best.pt \
              --data /home/ddwilde/scriptie/yaml/DOTA-stage2.yaml \
              --split test \
              --outdir /home/ddwilde/scriptie/results/test_stage2_saab

python val.py --weights /home/ddwilde/scriptie/runs/dota_lower/stage2-lower/weights/best.pt \
              --data /home/ddwilde/scriptie/yaml/DOTA-stage2.yaml \
              --split test \
              --outdir /home/ddwilde/scriptie/results/test_stage2_lower

mv /home/ddwilde/scriptie/datasets/dota-yolo-stage2/test/images/ /home/ddwilde/scriptie/datasets/dota-yolo-stage3/test/
mv /home/ddwilde/scriptie/datasets/dota-yolo-stage2/train/images/ /home/ddwilde/scriptie/datasets/dota-yolo-stage3/train/
mv /home/ddwilde/scriptie/datasets/dota-yolo-stage2/val/images/ /home/ddwilde/scriptie/datasets/dota-yolo-stage3/val/

python val.py --weights /home/ddwilde/scriptie/runs/dota_saab/stage3-saab/weights/best.pt \
              --data /home/ddwilde/scriptie/yaml/DOTA-stage3.yaml \
              --split test \
              --outdir /home/ddwilde/scriptie/results/test_stage3_saab

python val.py --weights /home/ddwilde/scriptie/runs/dota_lower/stage3-lower/weights/best.pt \
              --data /home/ddwilde/scriptie/yaml/DOTA-stage3.yaml \
              --split test \
              --outdir /home/ddwilde/scriptie/results/test_stage3_lower