#!/bin/bash
#SBATCH --job-name=lower-all
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --partition=gpu_h100 
#SBATCH --gpus-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --output=logs/lower-all-%j.out
#SBATCH --error=logs/lower-all-%j.err

module purge
module load 2023
module load CUDA/12.4.0
module spider Python/3.11.3-GCCcore-12.3.0
module load Python/3.11.3-GCCcore-12.3.0

source $HOME/ednet_env/bin/activate
cd $HOME/scriptie

python train.py \
  --cfg $HOME/scriptie/cfg/models/ednet/ednet-s.yaml \
  --data $HOME/scriptie/yaml/DOTA-stage1.yaml \
  --epochs 50 \
  --imgsz 640 \
  --batch-size 8 \
  --project $HOME/scriptie/runs/dota_lower2 \
  --name stage1-lower \
  --workers 8 \
  --weights pretrained/small.pt

python train.py \
  --cfg $HOME/scriptie/cfg/models/ednet/ednet-s.yaml \
  --data $HOME/scriptie/yaml/DOTA-stage2.yaml \
  --epochs 50 \
  --imgsz 640 \
  --batch-size 8 \
  --project $HOME/scriptie/runs/dota_lower2 \
  --name stage2-lower \
  --workers 8 \
  --weights /home/ddwilde/scriptie/runs/dota_lower2/stage1-lower/weights/best.pt

python train.py \
  --cfg $HOME/scriptie/cfg/models/ednet/ednet-s.yaml \
  --data $HOME/scriptie/yaml/DOTA-stage3.yaml \
  --epochs 50 \
  --imgsz 640 \
  --batch-size 8 \
  --project $HOME/scriptie/runs/dota_lower2 \
  --name stage3-lower \
  --workers 8 \
  --weights /home/ddwilde/scriptie/runs/dota_lower2/stage2-lower/weights/best.pt
