#!/bin/bash
#SBATCH --job-name=lower-stage3
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --partition=gpu_a100 
#SBATCH --gpus-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --output=logs/lower-stage3-%j.out
#SBATCH --error=logs/lower-stage3-%j.err

module purge
module load 2025
module load CUDA/12.8.0
module load Python/3.11.3-GCCcore-12.3.0

source $HOME/ednet_env/bin/activate
cd $HOME/scriptie

python train.py \
  --cfg $HOME/scriptie/cfg/models/ednet/ednet-s.yaml \
  --data $HOME/scriptie/yaml/DOTA-stage3.yaml \
  --epochs 50 \
  --imgsz 640 \
  --batch-size 8 \
  --project $HOME/scriptie/runs/dota_lower \
  --name stage3-lower \
  --workers 8 \
  --weights $HOME/scriptie/runs/dota_lower/stage2-lower/weights/best.pt
