#!/bin/bash
#SBATCH --job-name=saab-stage-all
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --partition=gpu_a100 
#SBATCH --gpus-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --output=logs/saab-stage-all-%j.out
#SBATCH --error=logs/saab-stage-all-%j.err

module purge
module load 2023
module load CUDA/12.4.0
module load Python/3.11.3-GCCcore-12.3.0

source $HOME/ednet_env/bin/activate
cd $HOME/scriptie

python train.py \
    --cfg /home/ddwilde/scriptie/ednet/cfg/models/ednet/ednet-s.yaml \
    --data /home/ddwilde/scriptie/yaml/DOTA-stage1.yaml \
    --epochs 15 \
    --imgsz 640 \
    --batch-size 4 \
    --project /home/ddwilde/scriptie/runs/dota_saab \
    --name stage1-saab \
    --workers 8 \
    --weights /home/ddwilde/scriptie/pretrained/small.pt \
    --override lora.enable=True \
    --override lora.freeze_backbone=True \
    --override replay.enable=True \
    --override replay.buffer_per_class=128 \
    --override replay.sample_per_batch=8 \
    --override replay.loss_weight=0.5 \
    --override replay.tiny_max_pixels=256

mv /home/ddwilde/scriptie/datasets/dota-yolo-stage1/test/images/ /home/ddwilde/scriptie/datasets/dota-yolo-stage2/test/
mv /home/ddwilde/scriptie/datasets/dota-yolo-stage1/train/images/ /home/ddwilde/scriptie/datasets/dota-yolo-stage2/train/
mv /home/ddwilde/scriptie/datasets/dota-yolo-stage1/val/images/ /home/ddwilde/scriptie/datasets/dota-yolo-stage2/val/

python train.py \
  --cfg /home/ddwilde/scriptie/ednet/cfg/models/ednet/ednet-s.yaml \
  --data /home/ddwilde/scriptie/yaml/DOTA-stage2.yaml \
  --epochs 15 \
  --imgsz 640 \
  --batch-size 4 \
  --project /home/ddwilde/scriptie/runs/dota_saab \
  --name stage2-saab \
  --workers 8 \
  --weights /home/ddwilde/scriptie/runs/dota_saab/stage1-saab/weights/best.pt \
  --override lora.enable=True \
  --override lora.freeze_backbone=True \
  --override replay.enable=True \
  --override replay.buffer_per_class=128 \
  --override replay.sample_per_batch=8 \
  --override replay.loss_weight=0.5 \
  --override replay.init_buffer=/home/ddwilde/scriptie/runs/dota_saab/stage1-saab/replay/buffer.pt \
  --override replay.memory_dir=/home/ddwilde/scriptie/datasets/memory/stage1 \
  --override replay.memory_ratio=0.25 \
  --override replay.tiny_max_pixels=256

mv /home/ddwilde/scriptie/datasets/dota-yolo-stage2/test/images/ /home/ddwilde/scriptie/datasets/dota-yolo-stage3/test/
mv /home/ddwilde/scriptie/datasets/dota-yolo-stage2/train/images/ /home/ddwilde/scriptie/datasets/dota-yolo-stage3/train/
mv /home/ddwilde/scriptie/datasets/dota-yolo-stage2/val/images/ /home/ddwilde/scriptie/datasets/dota-yolo-stage3/val/

python train.py \
  --cfg /home/ddwilde/scriptie/ednet/cfg/models/ednet/ednet-s.yaml \
  --data /home/ddwilde/scriptie/yaml/DOTA-stage3.yaml \
  --epochs 15 \
  --imgsz 640 \
  --batch-size 4 \
  --project /home/ddwilde/scriptie/runs/dota_saab \
  --name stage3-saab \
  --workers 8 \
  --weights /home/ddwilde/scriptie/runs/dota_saab/stage2-saab/weights/best.pt \
  --override lora.enable=True \
  --override lora.freeze_backbone=True \
  --override replay.enable=True \
  --override replay.buffer_per_class=128 \
  --override replay.sample_per_batch=8 \
  --override replay.loss_weight=0.5 \
  --override replay.init_buffer=/home/ddwilde/scriptie/runs/dota_saab/stage2-saab/replay/buffer.pt \
  --override replay.memory_dir=/home/ddwilde/scriptie/datasets/memory/stage3 \
  --override replay.memory_ratio=0.25 \
  --override replay.tiny_max_pixels=256
