#!/bin/bash
#SBATCH --job-name=saab-stage-all
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --partition=gpu_a100 
#SBATCH --gpus-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --output=logs/upper_saab-stage-all-%j.out
#SBATCH --error=logs/upper_saab-stage-all-%j.err

module purge
module load 2023
module load CUDA/12.4.0
module load Python/3.11.3-GCCcore-12.3.0

source $HOME/ednet_env/bin/activate
cd $HOME/scriptie

python train.py \
    --cfg /home/ddwilde/scriptie/ednet/cfg/models/ednet/ednet-s.yaml \
    --data /home/ddwilde/scriptie/yaml/DOTA.yaml \
    --epochs 50 \
    --imgsz 640 \
    --batch-size 4 \
    --project /home/ddwilde/scriptie/runs/dota_saab_upper \
    --name upper-saab \
    --workers 8 \
    --weights /home/ddwilde/scriptie/pretrained/small.pt \