#!/bin/bash
#SBATCH --job-name=lora-all
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --partition=gpu_a100 
#SBATCH --gpus-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --output=logs/lora-all-%j.out
#SBATCH --error=logs/lora-all-%j.err

module purge
module load 2023
module load CUDA/12.4.0
module load Python/3.11.3-GCCcore-12.3.0

source $HOME/ednet_env/bin/activate
cd $HOME/scriptie

python train.py \
  --cfg $HOME/scriptie/cfg/models/ednet/ednet-s.yaml \
  --data $HOME/scriptie/yaml/DOTA-stage1.yaml \
  --epochs 50 \
  --imgsz 640 \
  --batch-size 4 \
  --project $HOME/scriptie/runs/dota_lora2 \
  --name stage1-lora \
  --workers 8 \
  --weights pretrained/small.pt \
  --override lora.enable=True \
  --override "lora.feature_pyramid_indices=[13,16,19,22,25,28]" \
  --override lora.include_detection_head=False \
  --override lora.rank=32 \
  --override lora.alpha=32 \
  --override "freeze=[0,1,2,3,4,5,6,7,8,9,10,11,12,14,15,17,18,20,21,23,24,26,27]" 


python train.py \
  --cfg $HOME/scriptie/cfg/models/ednet/ednet-s.yaml \
  --data $HOME/scriptie/yaml/DOTA-stage2.yaml \
  --epochs 50 \
  --imgsz 640 \
  --batch-size 4 \
  --project $HOME/scriptie/runs/dota_lora2 \
  --name stage2-lora \
  --workers 8 \
  --weights /home/ddwilde/scriptie/runs/dota_lora2/stage1-lora/weights/best.pt \
  --override lora.enable=True \
  --override "lora.feature_pyramid_indices=[13,16,19,22,25,28]" \
  --override lora.include_detection_head=False \
  --override lora.rank=32 \
  --override lora.alpha=32 \
  --override "freeze=[0,1,2,3,4,5,6,7,8,9,10,11,12,14,15,17,18,20,21,23,24,26,27]" 


python train.py \
  --cfg $HOME/scriptie/cfg/models/ednet/ednet-s.yaml \
  --data $HOME/scriptie/yaml/DOTA-stage3.yaml \
  --epochs 50 \
  --imgsz 640 \
  --batch-size 4 \
  --project $HOME/scriptie/runs/dota_lora2 \
  --name stage3-lora \
  --workers 8 \
  --weights /home/ddwilde/scriptie/runs/dota_lora2/stage2-lora/weights/best.pt \
  --override lora.enable=True \
  --override "lora.feature_pyramid_indices=[13,16,19,22,25,28]" \
  --override lora.include_detection_head=False \
  --override lora.rank=32 \
  --override lora.alpha=32 \
  --override "freeze=[0,1,2,3,4,5,6,7,8,9,10,11,12,14,15,17,18,20,21,23,24,26,27]" `