#!/bin/bash
#SBATCH --job-name=saab-stage3
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --partition=gpu_a100 
#SBATCH --gpus-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --output=logs/saab-stage3-%j.out
#SBATCH --error=logs/saab-stage3-%j.err

module purge
module load 2025
module load CUDA/12.8.0
module load Python/3.11.3-GCCcore-12.3.0

source $HOME/ednet_env/bin/activate
cd $HOME/scriptie

python train.py \
  --cfg /home/ddwilde/scriptie/ednet/cfg/models/ednet/ednet-s.yaml \
  --data /home/ddwilde/scriptie/yaml/DOTA-stage3.yaml \
  --epochs 50 \
  --imgsz 640 \
  --batch-size 8 \
  --project /home/ddwilde/scriptie/runs/dota_saab \
  --name stage3-saab \
  --workers 8 \
  --weights /home/ddwilde/scriptie/runs/dota_saab/stage2-saab/weights/best.pt \
  --override lora.enable=True \
  --override lora.freeze_backbone=True \
  --override replay.enable=True \
  --override replay.buffer_per_class=128 \
  --override replay.sample_per_batch=16 \
  --override replay.loss_weight=0.5 \
  --override replay.init_buffer=/home/ddwilde/scriptie/runs/dota_saab/stage2-saab/replay/buffer.pt
